# Generated by Django 3.1.2 on 2020-10-28 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_until',
            field=models.DateField(default=datetime.date(2020, 10, 27)),
        ),
    ]
