# Generated by Django 3.1.2 on 2020-10-28 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premium', '0003_auto_20201028_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_one', models.CharField(max_length=254)),
                ('address_line_two', models.CharField(max_length=254)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('price_paid', models.FloatField()),
                ('days_given', models.IntegerField()),
                ('ppackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premium.premiumpackage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
