# Generated by Django 3.1.2 on 2020-10-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='created_for',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='sub_category',
        ),
        migrations.AlterField(
            model_name='event',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
