# Generated by Django 3.1.2 on 2020-10-29 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typesandcategories', '0004_auto_20201029_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'Inprogress'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('closed_on', models.DateTimeField(blank=True)),
                ('open_notes', models.TextField(blank=True)),
                ('close_notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='typesandcategories.eventsubcategory')),
            ],
        ),
    ]
