# Generated by Django 3.1.2 on 2020-10-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
