# Generated by Django 3.1.2 on 2020-10-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typesandcategories', '0003_eventsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='eventsubcategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
