# Generated by Django 3.1.2 on 2020-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_premiumpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpackage',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
